[tox]
envlist =
    tests_coverage
    check_format
    check_lint


[testenv:tests_coverage]
deps =
    pytest
    coverage
    requests
    hypothesis
extras = stackexchange
commands =
    coverage erase
    # Config is all specified in .coveragerc
    # Doctests are currently disabled and will return eventually.
    # coverage run -m pytest --doctest-modules
    coverage run -m pytest 
    coverage combine
    coverage html
    coverage report
commands_post =
    coverage erase


[testenv:check_lint]
deps = 
    pylint
    pytest
    requests
extras = stackexchange
commands = pylint hyperreal tests


[testenv:check_format]
deps = 
    black>=23.1.0
    isort
skip_install = true
commands = 
    black --check hyperreal tests
    isort --check --diff hyperreal tests


[testenv:apply_format]
# These applies the same format rules as check_format checks,
# just in one convenient tox commands.
deps = 
    black>=23.1.0
    isort
skip_install = true
commands = 
    black hyperreal tests
    isort hyperreal tests


[testenv:publish_package]
setenv =
    TWINE_USERNAME = __token__
passenv =
    TWINE_PASSWORD
allowlist_externals =
    rm
deps =
    build
    twine
commands =
    - rm -rf dist
    python -m build --wheel
    python -m build --sdist
    python -m twine upload dist/*
